<?php

declare(strict_types=1);

namespace BalatD\DevMcp\Install;

use TYPO3\CMS\Core\Information\Typo3Version;
use TYPO3\CMS\Core\Package\PackageManager;

/**
 * Boost analog: the composed AI guidelines. Selects guideline markdown from
 * Resources/Private/Guidelines by installed TYPO3 version and packages,
 * writes the composed file to .ai/guidelines/typo3.md and links it from
 * CLAUDE.md / AGENTS.md between idempotent markers.
 */
final class GuidelineComposer
{
    private const MARKER_START = '<!-- typo3-dev-mcp:guidelines:start -->';

    private const MARKER_END = '<!-- typo3-dev-mcp:guidelines:end -->';

    public function __construct(
        private readonly PackageManager $packageManager,
        private readonly DdevDetector $ddevDetector,
    ) {
    }

    /**
     * @return list<string> the guideline file names that apply to this installation
     */
    public function selectGuidelines(): array
    {
        $typo3Version = new Typo3Version();

        $files = [
            'general.md',
            'core-' . $typo3Version->getMajorVersion() . '.md',
            'fluid.md',
            'tca.md',
            'extbase.md',
            'testing.md',
        ];

        if ($this->ddevDetector->isDdevProject()) {
            $files[] = 'ddev.md';
        }

        return array_values(array_filter(
            $files,
            fn (string $file): bool => is_file($this->getGuidelinesPath() . '/' . $file),
        ));
    }

    public function compose(): string
    {
        $typo3Version = new Typo3Version();
        $replacements = [
            '{{typo3Version}}' => $typo3Version->getVersion(),
            '{{typo3Major}}' => (string)$typo3Version->getMajorVersion(),
            '{{phpVersion}}' => PHP_VERSION,
        ];

        $sections = [];
        foreach ($this->selectGuidelines() as $file) {
            $sections[] = trim(strtr(
                (string)file_get_contents($this->getGuidelinesPath() . '/' . $file),
                $replacements,
            ));
        }

        return "<!-- Generated by `typo3 devmcp:install` — re-run after upgrades. Do not edit manually. -->\n\n"
            . implode("\n\n", $sections) . "\n";
    }

    /**
     * @return list<string> paths of all written/updated files
     */
    public function install(string $projectPath): array
    {
        $projectPath = rtrim($projectPath, '/');
        $guidelineFile = $projectPath . '/.ai/guidelines/typo3.md';

        if (!is_dir(\dirname($guidelineFile)) && !mkdir(\dirname($guidelineFile), 0775, true)) {
            throw new \RuntimeException('Could not create directory ' . \dirname($guidelineFile));
        }
        file_put_contents($guidelineFile, $this->compose());

        $written = [$guidelineFile];
        $written[] = $this->linkInAgentFile(
            $projectPath . '/CLAUDE.md',
            "@.ai/guidelines/typo3.md\n",
        );
        $written[] = $this->linkInAgentFile(
            $projectPath . '/AGENTS.md',
            "Follow the TYPO3 guidelines in [.ai/guidelines/typo3.md](.ai/guidelines/typo3.md).\n",
        );

        return $written;
    }

    /**
     * Replaces the marker block if present, appends it otherwise.
     */
    private function linkInAgentFile(string $file, string $blockContent): string
    {
        $block = self::MARKER_START . "\n" . $blockContent . self::MARKER_END;
        $content = is_file($file) ? (string)file_get_contents($file) : '';

        $pattern = '/' . preg_quote(self::MARKER_START, '/') . '.*?' . preg_quote(self::MARKER_END, '/') . '/s';
        if (preg_match($pattern, $content) === 1) {
            $content = (string)preg_replace($pattern, $block, $content);
        } else {
            $content = rtrim($content) === ''
                ? $block . "\n"
                : rtrim($content) . "\n\n" . $block . "\n";
        }

        file_put_contents($file, $content);

        return $file;
    }

    private function getGuidelinesPath(): string
    {
        return $this->packageManager->getPackage('dev_mcp')->getPackagePath()
            . 'Resources/Private/Guidelines';
    }
}
