<?php

declare(strict_types=1);

namespace BalatD\DevMcp\Install;

use TYPO3\CMS\Core\Information\Typo3Version;
use TYPO3\CMS\Core\Package\PackageManager;

/**
 * Boost analog: the composed AI guidelines. Renders the guideline markdown from
 * Resources/Private/Guidelines, writes it to .ai/guidelines/typo3.md and links
 * it from CLAUDE.md / AGENTS.md between idempotent markers.
 *
 * The file documents which tools exist and what each reports. Framework advice
 * deliberately stays out of it: an agent already knows TYPO3, and every line
 * here is context on every request.
 */
final class GuidelineComposer
{
    private const GUIDELINE_FILE = 'general.md';

    private const MARKER_START = '<!-- typo3-dev-mcp:guidelines:start -->';

    private const MARKER_END = '<!-- typo3-dev-mcp:guidelines:end -->';

    public function __construct(
        private readonly PackageManager $packageManager,
    ) {
    }

    public function compose(): string
    {
        $typo3Version = new Typo3Version();

        $body = trim(strtr(
            (string)file_get_contents($this->getGuidelinesPath() . '/' . self::GUIDELINE_FILE),
            [
                '{{typo3Version}}' => $typo3Version->getVersion(),
                '{{phpVersion}}' => PHP_VERSION,
            ],
        ));

        return "<!-- Generated by `typo3 devmcp:install` — re-run after upgrades. Do not edit manually. -->\n\n"
            . $body . "\n";
    }

    /**
     * @return list<string> paths of all written/updated files
     */
    public function install(string $projectPath): array
    {
        $projectPath = rtrim($projectPath, '/');
        $guidelineFile = $projectPath . '/.ai/guidelines/typo3.md';

        if (!is_dir(\dirname($guidelineFile)) && !mkdir(\dirname($guidelineFile), 0775, true)) {
            throw new \RuntimeException('Could not create directory ' . \dirname($guidelineFile));
        }
        file_put_contents($guidelineFile, $this->compose());

        $written = [$guidelineFile];
        $written[] = $this->linkInAgentFile(
            $projectPath . '/CLAUDE.md',
            "@.ai/guidelines/typo3.md\n",
        );
        $written[] = $this->linkInAgentFile(
            $projectPath . '/AGENTS.md',
            "Follow the TYPO3 guidelines in [.ai/guidelines/typo3.md](.ai/guidelines/typo3.md).\n",
        );

        return $written;
    }

    /**
     * Replaces the marker block if present, appends it otherwise.
     */
    private function linkInAgentFile(string $file, string $blockContent): string
    {
        $block = self::MARKER_START . "\n" . $blockContent . self::MARKER_END;
        $content = is_file($file) ? (string)file_get_contents($file) : '';

        $pattern = '/' . preg_quote(self::MARKER_START, '/') . '.*?' . preg_quote(self::MARKER_END, '/') . '/s';
        if (preg_match($pattern, $content) === 1) {
            $content = (string)preg_replace($pattern, $block, $content);
        } else {
            $content = rtrim($content) === ''
                ? $block . "\n"
                : rtrim($content) . "\n\n" . $block . "\n";
        }

        file_put_contents($file, $content);

        return $file;
    }

    private function getGuidelinesPath(): string
    {
        return $this->packageManager->getPackage('dev_mcp')->getPackagePath()
            . 'Resources/Private/Guidelines';
    }
}
