<?php

declare(strict_types=1);

namespace BalatD\DevMcp\Install;

use TYPO3\CMS\Core\Information\Typo3Version;
use TYPO3\CMS\Core\Package\PackageManager;

/**
 * Boost analog: the composed AI guidelines. Renders the guideline markdown from
 * Resources/Private/Guidelines, writes it to .ai/guidelines/typo3.md, imports
 * that into CLAUDE.md and inlines it into AGENTS.md, both between idempotent
 * markers. Inlined because Codex and most other AGENTS.md readers do not follow
 * links or imports.
 *
 * The file documents which tools exist and what each reports. Framework advice
 * deliberately stays out of it: an agent already knows TYPO3, and every line
 * here is context on every request.
 *
 * @internal Not covered by the backwards-compatibility promise: tool
 *           response payloads and these implementation classes may change
 *           in any minor release.
 */
final class GuidelineComposer
{
    private const GUIDELINE_FILE = 'general.md';

    private const MARKER_START = '<!-- typo3-dev-mcp:guidelines:start -->';

    private const MARKER_END = '<!-- typo3-dev-mcp:guidelines:end -->';

    private const DDEV_HINT = ' It runs in DDEV: call PHP, Composer and the TYPO3 CLI through DDEV'
        . ' (`ddev exec php -l <file>`, `ddev composer <command>`, `ddev exec vendor/bin/typo3 <command>`),'
        . ' not on the host.';

    public function __construct(
        private readonly PackageManager $packageManager,
    ) {}

    public function compose(bool $viaDdev = false): string
    {
        $typo3Version = new Typo3Version();

        $body = trim(strtr(
            (string)file_get_contents($this->getGuidelinesPath() . '/' . self::GUIDELINE_FILE),
            [
                '{{typo3Version}}' => $typo3Version->getVersion(),
                '{{phpVersion}}' => PHP_VERSION,
                '{{ddev}}' => $viaDdev ? self::DDEV_HINT : '',
            ],
        ));

        return "<!-- Generated by `typo3 devmcp:install` — re-run after upgrades. Do not edit manually. -->\n\n"
            . $body . "\n";
    }

    /**
     * @return list<string> paths of all written/updated files
     */
    public function install(string $projectPath, bool $viaDdev = false): array
    {
        $projectPath = rtrim($projectPath, '/');
        $guidelineFile = $projectPath . '/.ai/guidelines/typo3.md';

        if (!is_dir(\dirname($guidelineFile)) && !mkdir(\dirname($guidelineFile), 0775, true)) {
            throw new \RuntimeException('Could not create directory ' . \dirname($guidelineFile));
        }
        $guidelines = $this->compose($viaDdev);
        file_put_contents($guidelineFile, $guidelines);

        $written = [$guidelineFile];
        $written[] = $this->writeMarkerBlock(
            $projectPath . '/CLAUDE.md',
            "@.ai/guidelines/typo3.md\n",
        );
        $written[] = $this->writeMarkerBlock($projectPath . '/AGENTS.md', $guidelines);

        return $written;
    }

    /**
     * Replaces the marker block if present, appends it otherwise.
     */
    private function writeMarkerBlock(string $file, string $blockContent): string
    {
        $block = self::MARKER_START . "\n" . $blockContent . self::MARKER_END;
        $content = is_file($file) ? (string)file_get_contents($file) : '';

        $pattern = '/' . preg_quote(self::MARKER_START, '/') . '.*?' . preg_quote(self::MARKER_END, '/') . '/s';
        if (preg_match($pattern, $content) === 1) {
            $content = (string)preg_replace_callback($pattern, static fn(): string => $block, $content);
        } else {
            $content = rtrim($content) === ''
                ? $block . "\n"
                : rtrim($content) . "\n\n" . $block . "\n";
        }

        file_put_contents($file, $content);

        return $file;
    }

    private function getGuidelinesPath(): string
    {
        return $this->packageManager->getPackage('dev_mcp')->getPackagePath()
            . 'Resources/Private/Guidelines';
    }
}
